version: "3"

services:
  app:
    tty: true
    restart: on-failure
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    env_file: .env
    environment:
      - DB_HOST=db
  db:
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data