version: "3"

services:
  app:
    tty: true
    restart: always
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    env_file: .env
    environment:
      - DB_HOST=db
  db:
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5